# Generated by Django 5.2.7 on 2025-10-19 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='content')),
                ('category', models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('review', 'Review'), ('nostalgia', 'Nostalgia')], default='category', max_length=100, verbose_name='Post Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pinned 📌')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes Count')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Dislikes Count')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
