# Generated by Django 5.2.7 on 2025-10-24 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Post')),
                ('content', models.TextField(help_text='Diskusi tentang Padel', verbose_name='Konten Lengkap')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Gambar Post')),
                ('video_link', models.URLField(blank=True, help_text='URL video platform eksternal', max_length=500, null=True, verbose_name='Tautan Video')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Diperbarui')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Terhapus?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Pembuat Post')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'permissions': [('manage_all_posts', 'Can manage all posts')],
            },
        ),
    ]
