# Generated by Django 5.2.7 on 2025-10-23 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Forum Post', 'verbose_name_plural': 'Forum Posts'},
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_posts/images/', verbose_name='Post Image'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Soft Deleted'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('review', 'Review'), ('nostalgia', 'Nostalgia')], default='discussion', max_length=100, verbose_name='Post Type'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.category', verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Post.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Like',
                'verbose_name_plural': 'Post Likes',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
