# Generated by Django 5.2.7 on 2025-10-23 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_category_options_alter_forumpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='forumpost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Comments Count'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Dislikes Count'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes Count'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['created_at'], name='Post_forump_created_c0d8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author'], name='Post_forump_author__892147_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['category'], name='Post_forump_categor_e3b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_pinned'], name='Post_forump_is_pinn_025639_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='Post_postli_post_id_a89122_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['created_at'], name='Post_postli_created_8c0933_idx'),
        ),
    ]
