# Generated by Django 5.2.7 on 2025-10-24 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_category_options_forumpost_comment_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Unggah gambar untuk post Anda', null=True, upload_to='forum_posts/images/', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned Post 📌'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='Masukkan URL video (YouTube/Vimeo)', max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['is_deleted'], name='Post_forump_is_dele_6b6c4d_idx'),
        ),
    ]
