# Generated by Django 5.2.7 on 2025-10-24 06:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_forumpost_author_alter_forumpost_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Forum Post', 'verbose_name_plural': 'Forum Posts'},
        ),
        migrations.RemoveIndex(
            model_name='forumpost',
            name='Post_forump_author__892147_idx',
        ),
        migrations.RemoveIndex(
            model_name='forumpost',
            name='Post_forump_categor_e3b2f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='forumpost',
            name='Post_forump_is_pinn_025639_idx',
        ),
        migrations.RemoveIndex(
            model_name='forumpost',
            name='Post_forump_is_dele_6b6c4d_idx',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='views',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Dislike'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Like'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='shares_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Share'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='video_link',
            field=models.URLField(blank=True, help_text='Opsional: Tautan video embed (YouTube/Vimeo)', null=True, validators=[django.core.validators.URLValidator()], verbose_name='Tautan Video'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(help_text='Isi konten postingan', verbose_name='Konten Post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Post ID'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Opsional: Unggah gambar pendukung', null=True, upload_to='post_images/', verbose_name='Gambar Post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Penanda soft delete untuk post', verbose_name='Dihapus?'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(help_text='Judul untuk postingan diskusi', max_length=255, verbose_name='Judul Post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', 'created_at'], name='Post_forump_author__a3b914_idx'),
        ),
        migrations.AddField(
            model_name='userpostinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.forumpost'),
        ),
        migrations.AddField(
            model_name='userpostinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.AlterUniqueTogether(
            name='userpostinteraction',
            unique_together={('user', 'post')},
        ),
    ]
