# Generated by Django 5.2.7 on 2025-10-21 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam atau iklan'), ('harassment', 'Pelecehan atau bullying'), ('inappropriate', 'Konten tidak pantas'), ('other', 'Lainnya')], default='other', max_length=20, verbose_name='Alasan Pelaporan')),
                ('description', models.TextField(blank=True, help_text='Jelaskan secara detail mengapa konten ini dilaporkan', null=True, verbose_name='Deskripsi Tambahan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status Laporan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Diselesaikan Pada')),
                ('admin_notes', models.TextField(blank=True, help_text='Catatan internal untuk moderator', null=True, verbose_name='Catatan Admin')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Diselesaikan Oleh')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='Report_repo_content_b7c2ed_idx'), models.Index(fields=['status', 'created_at'], name='Report_repo_status_de2b74_idx')],
            },
        ),
    ]
