# Generated by Django 5.2.7 on 2025-10-24 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SARA', 'Konten SARA'), ('SPAM', 'Spam'), ('NSFW', 'Konten Tidak Senonoh'), ('OTHER', 'Lainnya')], max_length=10, verbose_name='Kategori Laporan')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Deskripsi Tambahan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Review'), ('REVIEWED', 'Ditinjau'), ('RESOLVED', 'Selesai')], default='PENDING', max_length=10, verbose_name='Status Laporan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dilaporkan')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Ditinjau')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comment.comment', verbose_name='Komentar Dilaporkan')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='post.post', verbose_name='Post Dilaporkan')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Ditinjau Oleh')),
            ],
            options={
                'verbose_name': 'Laporan',
                'verbose_name_plural': 'Laporan',
                'ordering': ['-created_at'],
                'permissions': [('manage_all_reports', 'Can manage all reports')],
            },
        ),
    ]
