# Generated by Django 5.2.7 on 2025-10-24 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_reports_per_day', models.PositiveIntegerField(default=5, help_text='Batas jumlah laporan yang bisa dibuat user dalam sehari', verbose_name='Maksimal Laporan per Hari per User')),
                ('auto_reject_after_days', models.PositiveIntegerField(default=30, help_text='Laporan pending otomatis ditolak setelah hari tertentu', verbose_name='Auto Reject setelah Hari')),
                ('notify_admins_on_report', models.BooleanField(default=True, verbose_name='Notifikasi Admin pada Laporan Baru')),
                ('notify_reporter_on_update', models.BooleanField(default=True, verbose_name='Notifikasi Pelapor pada Update')),
                ('allow_anonymous_reports', models.BooleanField(default=False, verbose_name='Izinkan Laporan Anonim')),
                ('require_evidence', models.BooleanField(default=False, verbose_name='Wajibkan Bukti untuk Laporan Tertentu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Pelaporan',
                'verbose_name_plural': 'Pengaturan Pelaporan',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Deskripsi tindakan yang dilakukan terhadap konten yang dilaporkan', null=True, verbose_name='Tindakan yang Diambil'),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Unggah bukti pendukung (opsional)', null=True, upload_to='report_evidence/%Y/%m/%d/', verbose_name='Bukti Gambar'),
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_url',
            field=models.URLField(blank=True, help_text='Tautan ke bukti pendukung (opsional)', max_length=500, null=True, verbose_name='Tautan Bukti'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Jika dicentang, identitas pelapor tidak akan ditampilkan', verbose_name='Laporan Anonim'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Jenis Konten'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text='Jelaskan secara detail mengapa konten ini dilaporkan (maks 1000 karakter)', max_length=1000, null=True, verbose_name='Deskripsi Tambahan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.UUIDField(verbose_name='ID Konten'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('sara', 'Konten SARA (Suku, Agama, Ras, Antar-golongan)'), ('spam', 'Spam atau iklan tidak relevan'), ('harassment', 'Pelecehan atau bullying'), ('inappropriate', 'Konten tidak pantas/eksplisit'), ('copyright', 'Pelanggaran hak cipta'), ('other', 'Lainnya')], default='other', max_length=20, verbose_name='Alasan Pelaporan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Review'), ('under_review', 'Sedang Ditinjau'), ('resolved', 'Terselesaikan'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status Laporan'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'created_at'], name='Report_repo_reporte_65d30e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason', 'status'], name='Report_repo_reason_a5b741_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'under_review'])), fields=('reporter', 'content_type', 'object_id'), name='unique_report_per_user_content'),
        ),
    ]
