# Generated by Django 5.2.7 on 2025-10-24 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_reportsettings_report_action_taken_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reportsettings',
            options={'verbose_name': 'Report Settings', 'verbose_name_plural': 'Report Settings'},
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_user_content',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='Report_repo_reason_a5b741_idx',
        ),
        migrations.RenameField(
            model_name='reportsettings',
            old_name='notify_admins_on_report',
            new_name='notify_admin_on_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='report',
            name='evidence_image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='evidence_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='allow_anonymous_reports',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='auto_reject_after_days',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='max_reports_per_day',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='notify_reporter_on_update',
        ),
        migrations.RemoveField(
            model_name='reportsettings',
            name='require_evidence',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('sara', 'SARA (Suku, Agama, Ras, Antar-golongan)'), ('spam', 'Spam atau Iklan Tidak Sah'), ('inappropriate', 'Konten Tidak Senonoh'), ('harassment', 'Pelecehan atau Perundungan'), ('other', 'Lainnya')], default='other', max_length=20, verbose_name='Kategori Pelaporan'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Laporan dianggap selesai dan bisa diarsipkan', verbose_name='Terselesaikan?'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ditinjau pada'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Ditinjau oleh'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='auto_action_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Jumlah laporan minimum untuk tindakan otomatis', verbose_name='Threshold Auto Action'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='auto_hide_on_threshold',
            field=models.BooleanField(default=True, verbose_name='Sembunyikan Konten Otomatis pada Threshold'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='keep_resolved_reports_days',
            field=models.PositiveIntegerField(default=30, help_text='Laporan yang sudah resolved akan diarsipkan setelah hari ini', verbose_name='Menyimpan Laporan Terselesaikan (hari)'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diperbarui oleh'),
        ),
        migrations.AlterField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Catatan internal untuk tim moderasi', null=True, verbose_name='Catatan Admin'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dilaporkan pada'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, help_text='Jelaskan secara detail alasan pelaporan', null=True, verbose_name='Deskripsi Tambahan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Report ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.UUIDField(verbose_name='ID Objek'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'content_type', 'object_id'), name='unique_report_per_user_per_object'),
        ),
    ]
