# Generated by Django 5.2.7 on 2025-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_report_options_alter_reportsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.CharField(max_length=255, verbose_name='ID Objek'),
        ),
    ]
