# Generated by Django 5.2.7 on 2025-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField(blank=True, null=True)),
                ('delay', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
