# Generated by Django 5.2.7 on 2025-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_premiumsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='popup_delay_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
