# Generated by Django 5.2.7 on 2025-10-24 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Isi Komentar')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Reaksi Emoji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Diperbarui')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Like')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Terhapus?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment', verbose_name='Komentar Induk')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post', verbose_name='Post Terkait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentar',
                'ordering': ['-likes_count', '-created_at'],
                'permissions': [('manage_all_comments', 'Can manage all comments')],
            },
        ),
    ]
