# Generated by Django 5.2.7 on 2025-10-24 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Dislike'),
        ),
        migrations.CreateModel(
            name='CommentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, verbose_name='Jenis Interaksi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Dibuat')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='comment.comment', verbose_name='Komentar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Interaksi Komentar',
                'verbose_name_plural': 'Interaksi Komentar',
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
